### ISSUE TITLE
How to silence Gurobi

### ISSUE THREAD

**Issue by odow** [zidanessf/RDDP.jl#2]
I see you have lots of
https://github.com/zidanessf/RDDP.jl/blob/40e84119f9357503d7b8fb204b92c548734744d5/src/Algorithms.jl#L254

You can turn off printing with `set_silent(ro)`. 

You stop Gurobi from printing lots of academic licenses, re-use an environment. 
```Julia
const GRB_ENV = Gurobi.Env()
RDDP.buildMultiStageRobustModel(
    optimizer = () -> Gurobi.Optimizer(GRB_ENV),
) do ro, t
    set_silent(ro)
    # ...
end
```

**Comment by zidanessf** [comment]
Wow, nice suggestions. I finally get rid of these suppressors...

**Comment by zidanessf** [comment]
> I see you have lots of
> 
> https://github.com/zidanessf/RDDP.jl/blob/40e84119f9357503d7b8fb204b92c548734744d5/src/Algorithms.jl#L254
> 
> You can turn off printing with `set_silent(ro)`.
> 
> You stop Gurobi from printing lots of academic licenses, re-use an environment.
> 
> ```julia
> const GRB_ENV = Gurobi.Env()
> RDDP.buildMultiStageRobustModel(
>     optimizer = () -> Gurobi.Optimizer(GRB_ENV),
> ) do ro, t
>     set_silent(ro)
>     # ...
> end
> ```

Wow, nice suggestions. I finally get rid of these suppressors...

**Comment by odow** [comment]
Yeah it's documented here: https://github.com/jump-dev/Gurobi.jl#reusing-the-same-gurobi-environment-for-multiple-solves

But it's not actively advertised as a work-around for "turn off the printing" because it's a deliberate choice by Gurobi to have the academic licenses print, and Gurobi.jl is not an official Gurobi product.
